### ISSUE TITLE
SFTP::getServerPublicHostKey() fails when openssh server only has rsa hostkey and breaks the connection upon further use

### ISSUE THREAD

**Issue by hc-jworman** [phpseclib/phpseclib#1743]
I am using version 3.0.12.

It is failing here:
```php
// File: phpseclib/Net/SSH2.php
// Line: 4981
        if (!$key->verify($this->exchange_hash, $signature)) {
            return $this->disconnect_helper(NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE);
        };
```

If I continue to use the SFTP object afterwards it will not work and I get errors like "Invalid Size".
And from the server I get errors like "padding error: need 1580 block 8 mod 4" + "message authentication code incorrect"

But everything works fine if I do not call getServerPublicHostKey(). My current work around is to use reflection to manually retrieve the $server_public_host_key property.

```php
// Fails
$sftp = new SFTP(...);
$sftp->getServerPublicHostKey();
$sftp->put(...);

// Works
$sftp = new SFTP(...);
$sftp->put(...);
```

**Comment by terrafrost** [comment]
Could you give me the IP address or hostname of the machine that has the issue so that I could connect to that machine and try to reproduce the problem? I wouldn't need a username or password - the IP address / hostname itself (well and the port lol) should be sufficient. You could email that info to terrafrost@php.net if you didn't want to share it to the world.

Failing that, could you provide me with the SSH logs? You can get them by doing `define('NET_SSH2_LOGGING', 2)` at the top and then do `echo $sftp->getLog()` after wards.

Thanks!

**Comment by hc-jworman** [comment]
Sent an email with subject: "phpseclib/phpseclib Issue 1734"

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/decbde4f5d26dc688dd6dc7066e9923e2a9bff23 should fix this

**Comment by hc-jworman** [comment]
I pulled in these changes, but the signature still does not verify.
Did it work for you on the server we set up?

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/a748bf5beff829cc09178a178d14ba447fa540c4 should fix this.

Sorry about that!

Thanks!

**Comment by hc-jworman** [comment]
Everything seems to work now.
Thanks for all the help!

When can I expect a release?

**Comment by terrafrost** [comment]
Probably early next week!

**Comment by terrafrost** [comment]
A new version of phpseclib with this fix has been released.

Thanks!
