### ISSUE TITLE
chr(): Providing a value not in-between 0 and 255 is deprecated

### ISSUE THREAD

**Issue by SharkMachine** [phpseclib/phpseclib#2113]
I think this is something that didn't get fixed with the last release that fixed PHP 8.5 deprecations.

```
ErrorException: chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256

vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines/BCMath.php:157
```

SFTP connections fail for that reason for me. The setup I have is that warnings like these will throw an error.

**Comment by terrafrost** [comment]
I think https://github.com/phpseclib/phpseclib/commit/23ddb15c971461d0091467fca7d36565b2032b0b should fix this.

Thanks!

**Comment by terrafrost** [comment]
New versions of 1.0, 2.0 and 3.0, with this fix, have been released.

**Comment by MaximilianKresse** [comment]
With the current 2.0 version I'm still getting this error here:
```
chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256
vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2872
```

And this error:
```
chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256
vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2878
```

It's in another file but I think this is somewhat related to this issue here.

In the current 3.0 version this error also occurs:
```
chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256
vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA\PublicKey.php:244
```

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/652fb84669da1a8ac4f1adc9c28a7d45376fc9d8 should fix this.

Thanks!

**Comment by MaximilianKresse** [comment]
I found another one in 2.0:
```
chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256

vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger.php:3755
```

This only occurs in 2.0 and with bcmath disabled.

**Comment by flashwave** [comment]
I'm encountering this as well in 3.0:

```
Deprecated: chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256 in /[snip]/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA/PrivateKey.php on line 219
```

**Comment by terrafrost** [comment]
@MaximilianKresse - this commit should fix that:

https://github.com/phpseclib/phpseclib/commit/4b51d52335141d6d1a959a278a40c60575f17e67

Thanks for the heads up and apologies for the delay!

@flashwave - that was fixed in this commit:

http://github.com/phpseclib/phpseclib/commit/94bf93ecfb0ed3abc0911149a40bf1d1ae0c272d#diff-98197f14c4c223f5a85104c4266039014ebd5aad65dd869132777e556717e39bL219

That said, I haven't done a release since I implemented that fix. I'll try to do so this weekend assuming I don't lose power or whatever during the upcoming winter storm lol.

**Comment by terrafrost** [comment]
> That said, I haven't done a release since I implemented that fix. I'll try to do so this weekend assuming I don't lose power or whatever during the upcoming winter storm lol.

A new release has been made. Apologies for the delay.

Thanks!
