### ISSUE TITLE
INVALID HMAC

### ISSUE THREAD

**Issue by berni69** [phpseclib/phpseclib#916]
I'm trying to stablish a connection with a HP procurve from a SunOs 5.10 machine (PHP 5.3.9). But every time i'm getting the error "Invalid HMAC". The same code is working on a XAMPP server (Windows 8.1).

I'm using the lastest version of the library. I also tried the version 0.3X, but i have the same results.

I tried to comment and discard som algorithms but I had no success.

Do you know what's happening?

The logs of the connection:

```
<-
00000000  53:53:48:2d:31:2e:39:39:2d:43:6f:6d:77:61:72:65  SSH-1.99-Comware
00000010  2d:35:2e:32:30:2e:39:39:0a                       -5.20.99.

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:29:0d  b_2.0 (openssl).
00000020  0a                                               .

<- NET_SSH2_MSG_KEXINIT (since last: 0.0258, network: 0.0192s)
00000000  11:d5:ea:16:6b:39:0f:73:e8:f6:d4:3f:9e:37:29:a6  ....k9.s...?.7).
00000010  00:00:00:59:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...Ydiffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68:65  e-sha1,diffie-he
00000040  6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:34:2d:73:68  llman-group14-sh
00000050  61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61  a1,diffie-hellma
00000060  6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:00:00:00  n-group1-sha1...
00000070  0f:73:73:68:2d:64:73:73:2c:73:73:68:2d:72:73:61  .ssh-dss,ssh-rsa
00000080  00:00:00:1b:61:65:73:31:32:38:2d:63:62:63:2c:33  ....aes128-cbc,3
00000090  64:65:73:2d:63:62:63:2c:64:65:73:2d:63:62:63:00  des-cbc,des-cbc.
000000a0  00:00:1b:61:65:73:31:32:38:2d:63:62:63:2c:33:64  ...aes128-cbc,3d
000000b0  65:73:2d:63:62:63:2c:64:65:73:2d:63:62:63:00:00  es-cbc,des-cbc..
000000c0  00:2b:68:6d:61:63:2d:73:68:61:31:2c:68:6d:61:63  .+hmac-sha1,hmac
000000d0  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64  -sha1-96,hmac-md
000000e0  35:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00:00:00  5,hmac-md5-96...
000000f0  2b:68:6d:61:63:2d:73:68:61:31:2c:68:6d:61:63:2d  +hmac-sha1,hmac-
00000100  73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35  sha1-96,hmac-md5
00000110  2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00:00:00:04  ,hmac-md5-96....
00000120  6e:6f:6e:65:00:00:00:04:6e:6f:6e:65:00:00:00:00  none....none....
00000130  00:00:00:00:00:00:00:00:00                       .........

-> NET_SSH2_MSG_KEXINIT (since last: 0.02, network: 0s)
00000000  70:3d:ac:7f:97:42:a0:32:39:6b:c4:46:2f:9e:89:b9  p=...B.29k.F/...
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:de:61:72:63:66:6f:75:72  h-dss....arcfour
000000b0  32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61  256,arcfour128,a
000000c0  65:73:31:32:38:2d:63:74:72:2c:61:65:73:31:39:32  es128-ctr,aes192
000000d0  2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c  -ctr,aes256-ctr,
000000e0  74:77:6f:66:69:73:68:31:32:38:2d:63:74:72:2c:74  twofish128-ctr,t
000000f0  77:6f:66:69:73:68:31:39:32:2d:63:74:72:2c:74:77  wofish192-ctr,tw
00000100  6f:66:69:73:68:32:35:36:2d:63:74:72:2c:61:65:73  ofish256-ctr,aes
00000110  31:32:38:2d:63:62:63:2c:61:65:73:32:35:36:2d:63  128-cbc,aes256-c
00000120  62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:62  bc,twofish128-cb
00000130  63:2c:74:77:6f:66:69:73:68:31:39:32:2d:63:62:63  c,twofish192-cbc
00000140  2c:74:77:6f:66:69:73:68:32:35:36:2d:63:62:63:2c  ,twofish256-cbc,
00000150  74:77:6f:66:69:73:68:2d:63:62:63:2c:62:6c:6f:77  twofish-cbc,blow
00000160  66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66:69:73  fish-ctr,blowfis
00000170  68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72:2c:33  h-cbc,3des-ctr,3
00000180  64:65:73:2d:63:62:63:00:00:00:de:61:72:63:66:6f  des-cbc....arcfo
00000190  75:72:32:35:36:2c:61:72:63:66:6f:75:72:31:32:38  ur256,arcfour128
000001a0  2c:61:65:73:31:32:38:2d:63:74:72:2c:61:65:73:31  ,aes128-ctr,aes1
000001b0  39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74  92-ctr,aes256-ct
000001c0  72:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:74:72  r,twofish128-ctr
000001d0  2c:74:77:6f:66:69:73:68:31:39:32:2d:63:74:72:2c  ,twofish192-ctr,
000001e0  74:77:6f:66:69:73:68:32:35:36:2d:63:74:72:2c:61  twofish256-ctr,a
000001f0  65:73:31:32:38:2d:63:62:63:2c:61:65:73:32:35:36  es128-cbc,aes256
00000200  2d:63:62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d  -cbc,twofish128-
00000210  63:62:63:2c:74:77:6f:66:69:73:68:31:39:32:2d:63  cbc,twofish192-c
00000220  62:63:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:62  bc,twofish256-cb
00000230  63:2c:74:77:6f:66:69:73:68:2d:63:62:63:2c:62:6c  c,twofish-cbc,bl
00000240  6f:77:66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66  owfish-ctr,blowf
00000250  69:73:68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72  ish-cbc,3des-ctr
00000260  2c:33:64:65:73:2d:63:62:63:00:00:00:39:68:6d:61  ,3des-cbc...9hma
00000270  63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d  c-sha2-256,hmac-
00000280  73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68:61  sha1-96,hmac-sha
00000290  31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d  1,hmac-md5-96,hm
000002a0  61:63:2d:6d:64:35:00:00:00:39:68:6d:61:63:2d:73  ac-md5...9hmac-s
000002b0  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000002c0  31:2d:39:36:2c:68:6d:61:63:2d:73:68:61:31:2c:68  1-96,hmac-sha1,h
000002d0  6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d:61:63:2d  mac-md5-96,hmac-
000002e0  6d:64:35:00:00:00:04:6e:6f:6e:65:00:00:00:04:6e  md5....none....n
000002f0  6f:6e:65:00:00:00:00:00:00:00:00:00:00:00:00:00  one.............

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0701, network: 0s)
00000000  00:00:00:80:50:74:60:c1:cc:9c:e9:29:41:f2:87:e6  ....Pt`....)A...
00000010  17:10:b7:95:6f:49:fd:1e:e2:84:0d:55:aa:12:c9:03  ....oI.....U....
00000020  f4:41:a4:16:07:6d:c6:b5:b1:ea:f5:47:89:fb:4a:89  .A...m.....G..J.
00000030  4d:f2:d6:10:34:bf:87:0f:75:55:2a:5d:f1:38:7e:f7  M...4...uU*].8~.
00000040  e0:69:88:53:b5:f4:2e:4e:f4:33:61:ef:c7:db:ea:20  .i.S...N.3a....
00000050  dd:6b:76:85:5b:9d:91:9b:76:31:98:03:b4:39:bd:fc  .kv.[...v1...9..
00000060  99:25:f5:fb:9f:ce:b0:bc:34:bc:a5:b7:7d:ec:4b:9a  .%......4...}.K.
00000070  1e:c2:a6:48:7c:7a:66:56:ca:ec:a0:c2:c1:73:18:69  ...H|zfV.....s.i
00000080  33:a2:43:17                                      3.C.

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.6895, network: 0.6894s)
00000000  00:00:00:97:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:03:01:00:01:00:00:00:81:00:cb:fb:ec:55:e8  ..............U.
00000020  93:20:0d:38:69:e2:12:12:d1:51:ab:98:cc:60:aa:b5  . .8i....Q...`..
00000030  1c:19:4c:ac:10:67:6e:e1:67:9e:16:91:a1:31:2d:3d  ..L..gn.g....1-=
00000040  67:ce:ed:cc:c2:ba:54:22:c8:aa:5d:1c:56:e3:9e:a3  g.....T"..].V...
00000050  2f:7f:c5:19:4a:10:e5:ac:ce:7d:a6:61:90:55:86:c4  /...J....}.a.U..
00000060  92:d8:45:fe:5d:3d:b0:c6:ce:63:cc:97:a3:04:d7:ba  ..E.]=...c......
00000070  b7:33:c6:b6:39:41:0d:2f:01:3a:e6:b9:cb:ac:46:9f  .3..9A./.:....F.
00000080  48:13:85:db:3d:f9:c4:12:3d:57:e3:04:ec:22:51:11  H...=...=W..."Q.
00000090  e9:41:c1:66:06:83:64:1b:b7:68:71:00:00:00:81:00  .A.f..d..hq.....
000000a0  f8:e5:0c:29:43:6f:14:17:0b:33:0e:88:f9:85:d5:c0  ...)Co...3......
000000b0  e1:d5:cb:1c:3e:20:25:8f:a5:fa:8a:a9:f3:19:b9:60  ....> %........`
000000c0  47:ff:15:01:24:6f:5c:f5:48:79:34:c2:ee:6d:93:d7  G...$o\.Hy4..m..
000000d0  76:e7:37:48:f9:5c:74:cd:bd:9c:55:87:4d:e2:be:bd  v.7H.\t...U.M...
000000e0  31:82:06:83:93:d0:6f:c3:47:14:9b:a9:24:89:6a:a8  1.....o.G...$.j.
000000f0  17:88:43:d3:02:4d:9e:c3:28:6c:1c:96:e5:f0:30:61  ..C..M..(l....0a
00000100  b7:4a:1d:17:98:57:64:76:15:22:6e:1f:65:b2:8f:70  .J...Wdv."n.e..p
00000110  97:58:5b:76:ad:3f:00:c0:4a:8c:20:57:bc:3b:79:98  .X[v.?..J. W.;y.
00000120  00:00:00:8f:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000130  00:00:80:a4:2f:aa:97:47:86:27:a5:9f:ce:16:9d:37  ..../..G.'.....7
00000140  a0:fa:d1:b5:95:3c:72:77:5c:ac:fe:a6:b9:3d:80:f7  ......rw\....=..
00000150  55:48:58:2c:87:b9:98:37:e2:79:fb:d2:c3:3d:c3:f1  UHX,...7.y...=..
00000160  aa:e0:4a:35:67:ed:16:d0:ad:9f:e3:4d:cb:3f:ee:de  ..J5g......M.?..
00000170  60:eb:48:15:40:52:34:a7:9c:0a:bb:d4:78:8e:fc:2e  `.H.@R4.....x...
00000180  a2:2d:fc:80:80:2a:3a:fe:3e:fe:61:84:1a:ee:89:31  .-...*:.>.a....1
00000190  cd:49:ca:39:d4:c4:98:2b:fa:74:1c:96:2b:1c:5b:62  .I.9...+.t..+.[b
000001a0  5a:f9:57:e2:92:a2:0c:0f:4a:51:7e:0e:41:02:5f:3c  Z.W.....JQ~.A._.
000001b0  1c:2a:f7                                         .*.

-> NET_SSH2_MSG_NEWKEYS (since last: 0.0372, network: 0s)


<- NET_SSH2_MSG_NEWKEYS (since last: 0.0023, network: 0.0023s)


-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0157, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth


```

**Comment by terrafrost** [comment]
So you're able to connect to the HP procurve from XAMPP but not from SunOs 5.10? If so can you also post the logs of the connection from the XAMPP server?

My first guess would be that maybe commenting out these two lines in Net/SSH2.php would help:

```php
            'arcfour256',
            'arcfour128',
```

Would you be able to provide me with the IP address / port? If so you can email them to terrafrost@php.net. I wouldn't need a login to duplicate the problem - all I'd need is to be able to make a TCP connection.

**Comment by berni69** [comment]
Hi again,

Comennting the two lines didn't work. Here's the log connection:
```
<-
00000000  53:53:48:2d:31:2e:39:39:2d:43:6f:6d:77:61:72:65  SSH-1.99-Comware
00000010  2d:35:2e:32:30:2e:39:39:0a                       -5.20.99.

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:29:0d  b_2.0 (openssl).
00000020  0a                                               .

<- NET_SSH2_MSG_KEXINIT (since last: 0.0606, network: 0.0283s)
00000000  42:de:0a:df:a2:19:08:2e:26:24:7b:76:a0:c7:6e:14  B.......&${v..n.
00000010  00:00:00:59:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...Ydiffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68:65  e-sha1,diffie-he
00000040  6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:34:2d:73:68  llman-group14-sh
00000050  61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61  a1,diffie-hellma
00000060  6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:00:00:00  n-group1-sha1...
00000070  0f:73:73:68:2d:64:73:73:2c:73:73:68:2d:72:73:61  .ssh-dss,ssh-rsa
00000080  00:00:00:1b:61:65:73:31:32:38:2d:63:62:63:2c:33  ....aes128-cbc,3
00000090  64:65:73:2d:63:62:63:2c:64:65:73:2d:63:62:63:00  des-cbc,des-cbc.
000000a0  00:00:1b:61:65:73:31:32:38:2d:63:62:63:2c:33:64  ...aes128-cbc,3d
000000b0  65:73:2d:63:62:63:2c:64:65:73:2d:63:62:63:00:00  es-cbc,des-cbc..
000000c0  00:2b:68:6d:61:63:2d:73:68:61:31:2c:68:6d:61:63  .+hmac-sha1,hmac
000000d0  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64  -sha1-96,hmac-md
000000e0  35:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00:00:00  5,hmac-md5-96...
000000f0  2b:68:6d:61:63:2d:73:68:61:31:2c:68:6d:61:63:2d  +hmac-sha1,hmac-
00000100  73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35  sha1-96,hmac-md5
00000110  2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00:00:00:04  ,hmac-md5-96....
00000120  6e:6f:6e:65:00:00:00:04:6e:6f:6e:65:00:00:00:00  none....none....
00000130  00:00:00:00:00:00:00:00:00                       .........

-> NET_SSH2_MSG_KEXINIT (since last: 0.071, network: 0.0097s)
00000000  76:5f:4b:ba:97:3e:61:7b:39:34:20:aa:3f:61:ca:31  v_K..>a{94 .?a.1
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:c8:61:65:73:31:32:38:2d  h-dss....aes128-
000000b0  63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61  ctr,aes192-ctr,a
000000c0  65:73:32:35:36:2d:63:74:72:2c:74:77:6f:66:69:73  es256-ctr,twofis
000000d0  68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73:68  h128-ctr,twofish
000000e0  31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68:32  192-ctr,twofish2
000000f0  35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63:62  56-ctr,aes128-cb
00000100  63:2c:61:65:73:32:35:36:2d:63:62:63:2c:74:77:6f  c,aes256-cbc,two
00000110  66:69:73:68:31:32:38:2d:63:62:63:2c:74:77:6f:66  fish128-cbc,twof
00000120  69:73:68:31:39:32:2d:63:62:63:2c:74:77:6f:66:69  ish192-cbc,twofi
00000130  73:68:32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73  sh256-cbc,twofis
00000140  68:2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63  h-cbc,blowfish-c
00000150  74:72:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c  tr,blowfish-cbc,
00000160  33:64:65:73:2d:63:74:72:2c:33:64:65:73:2d:63:62  3des-ctr,3des-cb
00000170  63:00:00:00:c8:61:65:73:31:32:38:2d:63:74:72:2c  c....aes128-ctr,
00000180  61:65:73:31:39:32:2d:63:74:72:2c:61:65:73:32:35  aes192-ctr,aes25
00000190  36:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:32:38  6-ctr,twofish128
000001a0  2d:63:74:72:2c:74:77:6f:66:69:73:68:31:39:32:2d  -ctr,twofish192-
000001b0  63:74:72:2c:74:77:6f:66:69:73:68:32:35:36:2d:63  ctr,twofish256-c
000001c0  74:72:2c:61:65:73:31:32:38:2d:63:62:63:2c:61:65  tr,aes128-cbc,ae
000001d0  73:32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68  s256-cbc,twofish
000001e0  31:32:38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31  128-cbc,twofish1
000001f0  39:32:2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35  92-cbc,twofish25
00000200  36:2d:63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62  6-cbc,twofish-cb
00000210  63:2c:62:6c:6f:77:66:69:73:68:2d:63:74:72:2c:62  c,blowfish-ctr,b
00000220  6c:6f:77:66:69:73:68:2d:63:62:63:2c:33:64:65:73  lowfish-cbc,3des
00000230  2d:63:74:72:2c:33:64:65:73:2d:63:62:63:00:00:00  -ctr,3des-cbc...
00000240  39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68  9hmac-sha2-256,h
00000250  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
00000260  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
00000270  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39:68:6d  6,hmac-md5...9hm
00000280  61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63  ac-sha2-256,hmac
00000290  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68  -sha1-96,hmac-sh
000002a0  61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68  a1,hmac-md5-96,h
000002b0  6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e:65:00  mac-md5....none.
000002c0  00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00:00:00  ...none.........
000002d0  00:00:00:00                                      ....

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.4191, network: 0s)
00000000  00:00:00:80:76:42:ff:04:32:f4:11:6a:c0:c5:5a:c2  ....vB..2..j..Z.
00000010  e7:59:a2:7f:5f:fd:88:89:87:3c:df:34:42:6e:86:ea  .Y.._......4Bn..
00000020  c3:68:f7:cc:8b:7c:8e:82:f6:a4:e0:7f:25:0c:0a:2d  .h...|......%..-
00000030  f6:d7:22:42:c5:23:c1:d0:1e:a6:c9:4f:b4:74:24:73  .."B.#.....O.t$s
00000040  ab:c8:9e:47:d9:d1:29:27:93:a3:49:ac:3a:3e:4e:82  ...G..)'..I.:>N.
00000050  2d:a3:19:99:df:9b:a0:b8:8e:03:0c:8d:6f:a3:d9:98  -...........o...
00000060  a4:f1:f5:71:53:46:e8:de:5e:a3:8c:b1:36:89:17:e8  ...qSF..^...6...
00000070  9e:35:0a:ba:05:11:bb:8b:cd:0d:d3:ee:f2:bc:12:d6  .5..............
00000080  77:cf:76:70                                      w.vp

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.699, network: 0.6989s)
00000000  00:00:00:97:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:03:01:00:01:00:00:00:81:00:cb:fb:ec:55:e8  ..............U.
00000020  93:20:0d:38:69:e2:12:12:d1:51:ab:98:cc:60:aa:b5  . .8i....Q...`..
00000030  1c:19:4c:ac:10:67:6e:e1:67:9e:16:91:a1:31:2d:3d  ..L..gn.g....1-=
00000040  67:ce:ed:cc:c2:ba:54:22:c8:aa:5d:1c:56:e3:9e:a3  g.....T"..].V...
00000050  2f:7f:c5:19:4a:10:e5:ac:ce:7d:a6:61:90:55:86:c4  /...J....}.a.U..
00000060  92:d8:45:fe:5d:3d:b0:c6:ce:63:cc:97:a3:04:d7:ba  ..E.]=...c......
00000070  b7:33:c6:b6:39:41:0d:2f:01:3a:e6:b9:cb:ac:46:9f  .3..9A./.:....F.
00000080  48:13:85:db:3d:f9:c4:12:3d:57:e3:04:ec:22:51:11  H...=...=W..."Q.
00000090  e9:41:c1:66:06:83:64:1b:b7:68:71:00:00:00:81:00  .A.f..d..hq.....
000000a0  82:e3:ff:1c:ed:4b:b9:f8:6f:57:ec:d4:17:33:f1:41  .....K..oW...3.A
000000b0  d1:d2:2c:1e:3d:26:62:08:3b:87:39:6e:87:df:45:e7  ..,.=&b.;.9n..E.
000000c0  1e:b8:e5:79:70:d9:83:cc:19:20:a2:8f:f7:df:2e:d7  ...yp.... ......
000000d0  f3:49:88:0c:de:46:f5:ee:0a:06:80:55:fc:5c:52:ef  .I...F.....U.\R.
000000e0  ad:39:9f:50:e9:19:0d:a7:13:67:c5:58:c4:6c:8e:1b  .9.P.....g.X.l..
000000f0  6e:e4:c0:f9:13:3b:f6:69:f6:80:63:b0:4b:60:ec:6e  n....;.i..c.K`.n
00000100  af:45:bf:2f:c9:be:9e:4b:f9:16:d1:77:1e:91:d8:cf  .E./...K...w....
00000110  96:99:20:db:a9:d5:a8:68:2d:8e:3c:be:b0:c2:d5:00  .. ....h-.......
00000120  00:00:00:8f:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000130  00:00:80:5f:d8:ee:58:2f:e6:10:31:64:93:a4:94:96  ..._..X/..1d....
00000140  1b:9c:37:b3:5e:de:99:ad:d1:59:b5:91:8c:7a:cf:3d  ..7.^....Y...z.=
00000150  d4:35:eb:f2:42:e6:b0:8b:1a:13:4f:aa:d2:25:53:f7  .5..B.....O..%S.
00000160  a1:1d:f2:08:ce:c8:a5:bc:8b:7b:bd:89:5f:77:da:c7  .........{.._w..
00000170  bb:40:48:af:a7:db:4b:05:10:49:0b:ad:05:4e:be:e0  .@H...K..I...N..
00000180  78:36:47:54:6a:c6:79:59:e8:7c:a0:52:f1:ec:ec:c1  x6GTj.yY.|.R....
00000190  fe:06:fd:cf:4c:69:f6:f7:69:01:c4:ce:5f:1f:20:ae  ....Li..i..._. .
000001a0  43:c3:4f:2e:cf:81:3f:31:71:72:5a:03:00:99:2d:0f  C.O...?1qrZ...-.
000001b0  e1:ee:51                                         ..Q

-> NET_SSH2_MSG_NEWKEYS (since last: 0.0398, network: 0s)


<- NET_SSH2_MSG_NEWKEYS (since last: 0.0023, network: 0.0022s)


-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0237, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

Excepción capturada: Invalid HMAC

```
Provide you an IP address is not possible because it's inside a private network without internet connection.

If you want you can say me what do you want test and i run the test and send you the results/logs.

The last point is the log from the XAMPP server:

```
<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  33:2e:37:2e:31:70:32:0a                          3.7.1p2.

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_2.0 (openssl, 
00000020  62:63:6d:61:74:68:29:0d:0a                       bcmath)..

<- NET_SSH2_MSG_KEXINIT (since last: 3.2927, network: 0.0855s)
00000000  ad:26:c7:de:9d:9d:99:8b:46:2e:0e:1d:54:c6:1c:42  .&......F...T..B
00000010  00:00:00:3d:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...=diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68:65  e-sha1,diffie-he
00000040  6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68:61  llman-group1-sha
00000050  31:00:00:00:07:73:73:68:2d:72:73:61:00:00:00:0c  1....ssh-rsa....
00000060  64:65:73:2c:33:64:65:73:2d:63:62:63:00:00:00:0c  des,3des-cbc....
00000070  64:65:73:2c:33:64:65:73:2d:63:62:63:00:00:00:55  des,3des-cbc...U
00000080  68:6d:61:63:2d:6d:64:35:2c:68:6d:61:63:2d:73:68  hmac-md5,hmac-sh
00000090  61:31:2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36  a1,hmac-ripemd16
000000a0  30:2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30  0,hmac-ripemd160
000000b0  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61  @openssh.com,hma
000000c0  63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d  c-sha1-96,hmac-m
000000d0  64:35:2d:39:36:00:00:00:55:68:6d:61:63:2d:6d:64  d5-96...Uhmac-md
000000e0  35:2c:68:6d:61:63:2d:73:68:61:31:2c:68:6d:61:63  5,hmac-sha1,hmac
000000f0  2d:72:69:70:65:6d:64:31:36:30:2c:68:6d:61:63:2d  -ripemd160,hmac-
00000100  72:69:70:65:6d:64:31:36:30:40:6f:70:65:6e:73:73  ripemd160@openss
00000110  68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:31:2d  h.com,hmac-sha1-
00000120  39:36:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00:00  96,hmac-md5-96..
00000130  00:04:6e:6f:6e:65:00:00:00:04:6e:6f:6e:65:00:00  ..none....none..
00000140  00:00:00:00:00:00:00:00:00:00:00                 ...........

-> NET_SSH2_MSG_KEXINIT (since last: 0.0713, network: 0.0001s)
00000000  bf:af:22:83:43:c2:12:e5:e4:3c:2e:76:32:35:24:31  ..".C......v25$1
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:e9:61:72:63:66:6f:75:72  h-dss....arcfour
000000b0  32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61  256,arcfour128,a
000000c0  65:73:31:32:38:2d:63:74:72:2c:61:65:73:31:39:32  es128-ctr,aes192
000000d0  2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c  -ctr,aes256-ctr,
000000e0  74:77:6f:66:69:73:68:31:32:38:2d:63:74:72:2c:74  twofish128-ctr,t
000000f0  77:6f:66:69:73:68:31:39:32:2d:63:74:72:2c:74:77  wofish192-ctr,tw
00000100  6f:66:69:73:68:32:35:36:2d:63:74:72:2c:61:65:73  ofish256-ctr,aes
00000110  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000120  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:74:77  bc,aes256-cbc,tw
00000130  6f:66:69:73:68:31:32:38:2d:63:62:63:2c:74:77:6f  ofish128-cbc,two
00000140  66:69:73:68:31:39:32:2d:63:62:63:2c:74:77:6f:66  fish192-cbc,twof
00000150  69:73:68:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  ish256-cbc,twofi
00000160  73:68:2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d  sh-cbc,blowfish-
00000170  63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63  ctr,blowfish-cbc
00000180  2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73:2d:63  ,3des-ctr,3des-c
00000190  62:63:00:00:00:e9:61:72:63:66:6f:75:72:32:35:36  bc....arcfour256
000001a0  2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65:73:31  ,arcfour128,aes1
000001b0  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
000001c0  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:74:77:6f  r,aes256-ctr,two
000001d0  66:69:73:68:31:32:38:2d:63:74:72:2c:74:77:6f:66  fish128-ctr,twof
000001e0  69:73:68:31:39:32:2d:63:74:72:2c:74:77:6f:66:69  ish192-ctr,twofi
000001f0  73:68:32:35:36:2d:63:74:72:2c:61:65:73:31:32:38  sh256-ctr,aes128
00000200  2d:63:62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c  -cbc,aes192-cbc,
00000210  61:65:73:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  aes256-cbc,twofi
00000220  73:68:31:32:38:2d:63:62:63:2c:74:77:6f:66:69:73  sh128-cbc,twofis
00000230  68:31:39:32:2d:63:62:63:2c:74:77:6f:66:69:73:68  h192-cbc,twofish
00000240  32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68:2d  256-cbc,twofish-
00000250  63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:74:72  cbc,blowfish-ctr
00000260  2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c:33:64  ,blowfish-cbc,3d
00000270  65:73:2d:63:74:72:2c:33:64:65:73:2d:63:62:63:00  es-ctr,3des-cbc.
00000280  00:00:39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ..9hmac-sha2-256
00000290  2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d  ,hmac-sha1-96,hm
000002a0  61:63:2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35  ac-sha1,hmac-md5
000002b0  2d:39:36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39  -96,hmac-md5...9
000002c0  68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d  hmac-sha2-256,hm
000002d0  61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d  ac-sha1-96,hmac-
000002e0  73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  sha1,hmac-md5-96
000002f0  2c:68:6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e  ,hmac-md5....non
00000300  65:00:00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00  e....none.......
00000310  00:00:00:00:00:00                                ......

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0819, network: 0s)
00000000  00:00:00:81:00:95:d9:7a:22:7d:c5:18:ec:2a:43:ce  .......z"}...*C.
00000010  26:ec:9e:17:89:77:bf:c4:4d:4d:1d:fe:dd:df:f6:fa  &....w..MM......
00000020  7c:55:76:24:bb:c4:d7:78:32:37:c6:12:25:d5:a3:d8  |Uv$...x27..%...
00000030  be:92:4b:73:f4:0b:dc:11:f1:61:f9:c3:24:d4:4b:38  ..Ks.....a..$.K8
00000040  d9:8d:7c:d6:ff:7e:ca:de:86:8e:75:f7:9b:73:34:c5  ..|..~....u..s4.
00000050  5a:ab:e9:18:ce:45:75:f6:f2:a0:6c:c2:e2:0e:69:f6  Z....Eu...l...i.
00000060  a6:c6:5f:38:51:6e:81:0f:3f:a7:29:ec:6a:56:75:8d  .._8Qn..?.).jVu.
00000070  15:4a:41:2f:cc:7e:6e:45:f2:ba:53:20:82:d3:c2:dc  .JA/.~nE..S ....
00000080  29:96:6b:13:e3                                   ).k..

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.4691, network: 0.469s)
00000000  00:00:00:85:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:01:23:00:00:00:71:00:b6:09:c2:40:9a:7e:5b  ...#...q....@.~[
00000020  22:7e:0b:6e:7b:af:64:b6:12:5a:4d:81:32:f2:b7:80  "~.n{.d..ZM.2...
00000030  26:9b:d1:c0:2f:25:a1:20:2a:63:b0:05:fe:0c:2c:82  &.../%. *c....,.
00000040  6d:67:ac:1b:d1:e0:79:6d:fc:59:5c:2e:b5:fe:d8:9a  mg....ym.Y\.....
00000050  c0:a3:d1:89:be:94:45:07:39:c1:ae:bf:a9:5c:04:e5  ......E.9....\..
00000060  b7:f6:90:bd:cc:c3:ad:02:71:de:71:ff:18:75:19:e6  ........q.q..u..
00000070  52:e9:d7:d6:d0:0d:a0:61:07:ed:57:43:c5:ec:52:11  R......a..WC..R.
00000080  22:b7:c0:5d:8e:6f:90:9a:3b:00:00:00:80:0a:e9:47  "..].o..;......G
00000090  6f:44:20:1d:80:30:98:9f:56:ab:c7:ab:c7:fa:07:08  oD ..0..V.......
000000a0  0b:1b:bd:d1:09:98:6b:56:99:f2:bf:5b:b4:df:49:5e  ......kV...[..I^
000000b0  d0:32:bf:c4:c8:84:f1:23:7b:f8:f8:1d:e3:bb:19:3a  .2.....#{......:
000000c0  79:d1:5a:ea:91:22:5e:09:f7:64:5c:8c:4a:83:8a:4c  y.Z.."^..d\.J..L
000000d0  41:31:4e:f3:89:e1:4f:4b:5b:c5:09:78:92:06:21:ec  A1N...OK[..x..!.
000000e0  79:bd:94:2b:04:b9:64:78:10:6f:b0:6e:ca:5b:f5:92  y..+..dx.o.n.[..
000000f0  a6:fb:42:11:80:18:f7:9c:ac:1d:c2:0e:8e:75:01:ce  ..B..........u..
00000100  d8:92:71:f3:6b:dc:fc:42:4f:8c:40:3b:26:00:00:00  ..q.k..BO.@;&...
00000110  7f:00:00:00:07:73:73:68:2d:72:73:61:00:00:00:70  .....ssh-rsa...p
00000120  a4:f1:19:d9:91:f0:62:d8:74:61:e2:74:bc:a8:a6:62  ......b.ta.t...b
00000130  c3:d6:3f:4a:cc:95:f9:d9:e8:77:4b:f1:f0:63:0d:17  ..?J.....wK..c..
00000140  ad:71:22:7f:ed:d4:cd:42:e1:37:01:20:66:97:b3:ea  .q"....B.7. f...
00000150  c5:a0:78:18:12:28:c2:c9:bc:1d:71:1e:b3:22:d1:0f  ..x..(....q.."..
00000160  b5:2b:41:5e:94:c9:cd:f3:bf:3d:43:9e:aa:89:a8:d8  .+A^.....=C.....
00000170  69:b0:19:be:ce:a8:34:00:83:f1:66:a7:5f:7f:21:bd  i.....4...f._.!.
00000180  c1:6e:de:82:a8:56:39:56:77:ef:38:9d:33:cb:07:6b  .n...V9Vw.8.3..k

-> NET_SSH2_MSG_NEWKEYS (since last: 0.0159, network: 0.0001s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0001, network: 0s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0018, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.3149, network: 0.3148s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0002, network: 0.0001s)
00000000  00:00:00:08:75:73:65:72:6e:61:6d:65:00:00:00:0e  ....username....
00000010  73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00  ssh-connection..
00000020  00:08:70:61:73:73:77:6f:72:64:00:00:00:00:08:70  ..password.....p
00000030  61:73:73:77:6f:72:64                             assword

<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0634, network: 0.0633s)
```

**Comment by terrafrost** [comment]
Without being able to directly connect I am highly confident that this issue will simply go unresolved. This happens time and time again. Someone reports a problem, their SSH2 server winds up being in a LAN, and then when I ask for more info, they simply cease following up after a certain point. Example:

https://github.com/phpseclib/phpseclib/issues/895#issuecomment-163673885

Basically, debugging by proxy is a PITA for all parties involved. Instead of me making a change and finding out if that change achieved the desired effect instantly it could take 48h for me to find out if a single change worked (eg. I reply on Friday and you don't respond until Monday because you had weekend plans or some such). And that's just one change. In the course of diagnosing an issue I could make, who knows, maybe like 10-20 changes. Normally, it might take an hour to make all those changes, but with debugging by proxy...

I'd ask if you could give me limited VPN access but I suspect that won't happen so whatever.

In any event...

I note that on XAMPP you have bcmath but on the SunOs 5.10 machine you don't. I very seriously doubt this'll fix anything but I guess you could try enabling bcmath on the SunOs 5.10 machine.

I'd also check the sha1 hash of Net/SSH2.php on both the SunOs 5.10 machine and on the XAMPP machine, just to make sure that they're running the same versions.

Also, maybe just try brute forcing algorithms until you find one that works. ie. comment / uncomment out algorithms until you find one that works. This is something I could make a lot easier but, atm, I have other phpseclib priorities...

**Comment by berni69** [comment]
I send you a login to do the tests through de email. 

Thanks you for your help

**Comment by berni69** [comment]
I've updated the library with the latest version and the bug was corrected.

**Comment by peticel** [comment]
Hello,

Can you please specify the version of the library which worked for you? I'm using Centos 6.7, PHP 5.3.3, phpseclib1.0.1 but i still have the same error. I've already try to comment values from  $encryption_algorithms /  $kex_algorithms / $server_host_key_algorithms / $mac_algorithms but no success. Unfortunately remote access is not possible at all :(

Thanks.

**Comment by berni69** [comment]
upgrade your lib to the lastest avaiable in the respository. Use git clone
to get it

Cordialment,
Bernat Mut

2016-03-29 15:52 GMT+02:00 peticel <notifications@github.com>:

**Comment by terrafrost** [comment]
@peticel - you'd do well to post a new issue, as well, instead of replying to an existing one. Doing so will make it harder for me or others to lose track of your post.

That said, to assist you further I'd want to see logs. You can enable logging by doing `define('NET_SSH2_LOGGING', 2)` and then, later, doing `echo $ssh->getLog()`.

**Comment by peticel** [comment]
hello,

Thanks for the answer, the server has no access on internet this is way no remote access is possible, also i have to manually download all packages needed.

@terrafrost: i'll open a new post with this issue and give you there the required information.
